-- FinFlow: encerramento atômico de parceria e decisões individuais de caixinhas.

CREATE TABLE IF NOT EXISTS public.parceria_caixinha_decisoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parceria_id BIGINT NOT NULL,
  source_caixinha_id BIGINT NOT NULL,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  source_owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  meta_valor NUMERIC NOT NULL,
  saldo_total NUMERIC NOT NULL CHECK (saldo_total >= 0),
  cor TEXT NOT NULL,
  icone TEXT NOT NULL,
  data_prazo DATE,
  status TEXT NOT NULL DEFAULT 'pendente'
    CHECK (status IN ('pendente', 'mantida', 'descartada')),
  saldo_definido NUMERIC CHECK (saldo_definido >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ,
  UNIQUE (parceria_id, source_caixinha_id, user_id)
);

ALTER TABLE public.parceria_caixinha_decisoes ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.parceria_caixinha_decisoes FROM PUBLIC, anon;
GRANT SELECT ON TABLE public.parceria_caixinha_decisoes TO authenticated;
GRANT ALL ON TABLE public.parceria_caixinha_decisoes TO service_role;
REVOKE ALL ON SEQUENCE public.parceria_caixinha_decisoes_id_seq FROM PUBLIC, anon;
GRANT USAGE, SELECT ON SEQUENCE public.parceria_caixinha_decisoes_id_seq TO service_role;

DROP POLICY IF EXISTS parceria_caixinha_decisoes_owner_select
  ON public.parceria_caixinha_decisoes;
CREATE POLICY parceria_caixinha_decisoes_owner_select
  ON public.parceria_caixinha_decisoes
  FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

CREATE OR REPLACE FUNCTION public.iniciar_dissolucao_parceria(p_parceria_id BIGINT)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_uid UUID := auth.uid();
  v_parceria public.parcerias%ROWTYPE;
  v_decisoes INTEGER := 0;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'authentication required';
  END IF;

  SELECT *
    INTO v_parceria
    FROM public.parcerias
   WHERE id = p_parceria_id
     AND status = 'aceito'
     AND (solicitante_id = v_uid OR convidado_id = v_uid)
   FOR UPDATE;

  IF NOT FOUND OR v_parceria.convidado_id IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'active partnership not found';
  END IF;

  INSERT INTO public.parceria_caixinha_decisoes (
    parceria_id,
    source_caixinha_id,
    user_id,
    source_owner_id,
    nome,
    meta_valor,
    saldo_total,
    cor,
    icone,
    data_prazo
  )
  SELECT
    v_parceria.id,
    c.id,
    participante.user_id,
    c.user_id,
    c.nome,
    c.meta_valor,
    greatest(0, coalesce(c.saldo_atual, 0)),
    c.cor,
    c.icone,
    c.data_prazo
  FROM public.caixinhas c
  CROSS JOIN LATERAL (
    VALUES (v_parceria.solicitante_id), (v_parceria.convidado_id)
  ) AS participante(user_id)
  WHERE c.compartilhado IS TRUE
    AND c.user_id IN (v_parceria.solicitante_id, v_parceria.convidado_id)
  ON CONFLICT (parceria_id, source_caixinha_id, user_id) DO NOTHING;

  GET DIAGNOSTICS v_decisoes = ROW_COUNT;

  -- As caixinhas originais ficam ocultas até a decisão de seus proprietários.
  UPDATE public.caixinhas
     SET compartilhado = false,
         arquivado = true
   WHERE compartilhado IS TRUE
     AND user_id IN (v_parceria.solicitante_id, v_parceria.convidado_id);

  -- Cada conta permanece com quem a criou e deixa de ser compartilhada.
  UPDATE public.contas
     SET compartilhado = false
   WHERE compartilhado IS TRUE
     AND user_id IN (v_parceria.solicitante_id, v_parceria.convidado_id);

  DELETE FROM public.parcerias WHERE id = v_parceria.id;

  RETURN v_decisoes;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_minhas_decisoes_caixinha()
RETURNS TABLE (
  id BIGINT,
  nome TEXT,
  meta_valor NUMERIC,
  saldo_total NUMERIC,
  saldo_disponivel NUMERIC,
  cor TEXT,
  icone TEXT,
  data_prazo DATE
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
  SELECT
    d.id,
    d.nome,
    d.meta_valor,
    d.saldo_total,
    greatest(
      0,
      d.saldo_total - coalesce((
        SELECT sum(outra.saldo_definido)
        FROM public.parceria_caixinha_decisoes outra
        WHERE outra.parceria_id = d.parceria_id
          AND outra.source_caixinha_id = d.source_caixinha_id
          AND outra.user_id <> d.user_id
          AND outra.status = 'mantida'
      ), 0)
    ) AS saldo_disponivel,
    d.cor,
    d.icone,
    d.data_prazo
  FROM public.parceria_caixinha_decisoes d
  WHERE d.user_id = (SELECT auth.uid())
    AND d.status = 'pendente'
  ORDER BY d.created_at, d.id;
$function$;

CREATE OR REPLACE FUNCTION public.resolver_decisao_caixinha(
  p_decisao_id BIGINT,
  p_manter BOOLEAN,
  p_saldo NUMERIC DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_uid UUID := auth.uid();
  v_decisao public.parceria_caixinha_decisoes%ROWTYPE;
  v_ja_destinado NUMERIC := 0;
  v_disponivel NUMERIC := 0;
  v_updated INTEGER := 0;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'authentication required';
  END IF;

  -- Bloqueia as duas decisões da mesma caixinha para impedir saldo duplicado.
  PERFORM 1
    FROM public.parceria_caixinha_decisoes
   WHERE parceria_id = (
     SELECT parceria_id
       FROM public.parceria_caixinha_decisoes
      WHERE id = p_decisao_id AND user_id = v_uid
   )
     AND source_caixinha_id = (
       SELECT source_caixinha_id
         FROM public.parceria_caixinha_decisoes
        WHERE id = p_decisao_id AND user_id = v_uid
     )
   FOR UPDATE;

  SELECT *
    INTO v_decisao
    FROM public.parceria_caixinha_decisoes
   WHERE id = p_decisao_id
     AND user_id = v_uid
     AND status = 'pendente'
   FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'pending decision not found';
  END IF;

  SELECT coalesce(sum(saldo_definido), 0)
    INTO v_ja_destinado
    FROM public.parceria_caixinha_decisoes
   WHERE parceria_id = v_decisao.parceria_id
     AND source_caixinha_id = v_decisao.source_caixinha_id
     AND user_id <> v_uid
     AND status = 'mantida';

  v_disponivel := greatest(0, v_decisao.saldo_total - v_ja_destinado);

  IF p_manter THEN
    IF p_saldo IS NULL OR p_saldo < 0 OR p_saldo > v_disponivel THEN
      RAISE EXCEPTION USING
        ERRCODE = '22003',
        MESSAGE = 'balance must be between zero and the available balance';
    END IF;

    IF v_decisao.source_owner_id = v_uid THEN
      UPDATE public.caixinhas
         SET saldo_atual = p_saldo,
             compartilhado = false,
             arquivado = false
       WHERE id = v_decisao.source_caixinha_id
         AND user_id = v_uid;
      GET DIAGNOSTICS v_updated = ROW_COUNT;
    END IF;

    IF v_updated = 0 THEN
      INSERT INTO public.caixinhas (
        nome, meta_valor, saldo_atual, cor, icone, user_id,
        compartilhado, data_prazo, arquivado
      ) VALUES (
        v_decisao.nome,
        v_decisao.meta_valor,
        p_saldo,
        v_decisao.cor,
        v_decisao.icone,
        v_uid,
        false,
        v_decisao.data_prazo,
        false
      );
    END IF;

    UPDATE public.parceria_caixinha_decisoes
       SET status = 'mantida',
           saldo_definido = p_saldo,
           resolved_at = now()
     WHERE id = v_decisao.id;
  ELSE
    IF v_decisao.source_owner_id = v_uid THEN
      DELETE FROM public.caixinhas
       WHERE id = v_decisao.source_caixinha_id
         AND user_id = v_uid;
    END IF;

    UPDATE public.parceria_caixinha_decisoes
       SET status = 'descartada',
           saldo_definido = 0,
           resolved_at = now()
     WHERE id = v_decisao.id;
  END IF;
END;
$function$;

REVOKE ALL ON FUNCTION public.iniciar_dissolucao_parceria(BIGINT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_minhas_decisoes_caixinha() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.resolver_decisao_caixinha(BIGINT, BOOLEAN, NUMERIC) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.iniciar_dissolucao_parceria(BIGINT) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_minhas_decisoes_caixinha() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.resolver_decisao_caixinha(BIGINT, BOOLEAN, NUMERIC) TO authenticated, service_role;
