-- FinFlow: resumo persistente e separação das contas por participante.
--
-- Cada lançamento permanece com quem o criou. O dono conserva a conta
-- original; o outro participante recebe uma cópia individual apenas quando
-- possui saldo ou lançamentos próprios nela. As decisões de caixinhas da
-- migration anterior continuam sendo usadas.

BEGIN;

CREATE TABLE IF NOT EXISTS public.parceria_dissolucao_resumos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parceria_id BIGINT NOT NULL,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  iniciada_por UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  visto_em TIMESTAMPTZ,
  UNIQUE (parceria_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.parceria_dissolucao_itens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resumo_id BIGINT NOT NULL
    REFERENCES public.parceria_dissolucao_resumos(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL CHECK (tipo IN ('conta', 'caixinha')),
  source_id BIGINT NOT NULL,
  target_conta_id BIGINT,
  source_owner_id UUID NOT NULL,
  nome TEXT NOT NULL,
  saldo_final NUMERIC NOT NULL,
  possui_lancamentos BOOLEAN NOT NULL DEFAULT false,
  estado TEXT NOT NULL CHECK (
    estado IN ('informativo', 'pendente', 'mantida', 'arquivada', 'removida')
  ),
  resolved_at TIMESTAMPTZ,
  UNIQUE (resumo_id, tipo, source_id)
);

-- Contas que devem permanecer preservadas no banco, mas invisiveis somente
-- para o participante ao qual pertencem depois da dissolucao. Essa camada
-- evita que uma conta vazia reapareca tanto na lista ativa quanto no hub de
-- arquivadas, sem apagar o registro nem o resumo historico.
CREATE TABLE IF NOT EXISTS public.contas_ocultas_usuario (
  conta_id BIGINT NOT NULL
    REFERENCES public.contas(id) ON DELETE CASCADE,
  user_id UUID NOT NULL
    REFERENCES auth.users(id) ON DELETE CASCADE,
  resumo_id BIGINT NOT NULL
    REFERENCES public.parceria_dissolucao_resumos(id) ON DELETE CASCADE,
  motivo TEXT NOT NULL DEFAULT 'dissolucao_parceria',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (conta_id, user_id)
);

CREATE INDEX IF NOT EXISTS parceria_dissolucao_resumos_pendentes_idx
  ON public.parceria_dissolucao_resumos (user_id, created_at, id)
  WHERE visto_em IS NULL;

CREATE INDEX IF NOT EXISTS parceria_dissolucao_itens_pendentes_idx
  ON public.parceria_dissolucao_itens (resumo_id, tipo, estado, id);

CREATE INDEX IF NOT EXISTS contas_ocultas_usuario_owner_idx
  ON public.contas_ocultas_usuario (user_id, conta_id);

ALTER TABLE public.parceria_dissolucao_resumos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parceria_dissolucao_itens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contas_ocultas_usuario ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.parceria_dissolucao_resumos
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.parceria_dissolucao_itens
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.contas_ocultas_usuario
  FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.parceria_dissolucao_resumos TO authenticated;
GRANT SELECT ON TABLE public.parceria_dissolucao_itens TO authenticated;
GRANT ALL ON TABLE public.parceria_dissolucao_resumos TO service_role;
GRANT ALL ON TABLE public.parceria_dissolucao_itens TO service_role;
GRANT ALL ON TABLE public.contas_ocultas_usuario TO service_role;

REVOKE ALL ON SEQUENCE public.parceria_dissolucao_resumos_id_seq
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.parceria_dissolucao_itens_id_seq
  FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.parceria_dissolucao_resumos_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.parceria_dissolucao_itens_id_seq TO service_role;

DROP POLICY IF EXISTS parceria_dissolucao_resumos_owner_select
  ON public.parceria_dissolucao_resumos;
CREATE POLICY parceria_dissolucao_resumos_owner_select
  ON public.parceria_dissolucao_resumos
  FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS parceria_dissolucao_itens_owner_select
  ON public.parceria_dissolucao_itens;
CREATE POLICY parceria_dissolucao_itens_owner_select
  ON public.parceria_dissolucao_itens
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.parceria_dissolucao_resumos r
      WHERE r.id = parceria_dissolucao_itens.resumo_id
        AND r.user_id = (SELECT auth.uid())
    )
  );

-- A funcao e SECURITY DEFINER para que a policy de contas consiga consultar
-- a tabela interna sem expor essa tabela ao cliente autenticado.
CREATE OR REPLACE FUNCTION public.conta_visivel_para_usuario(
  p_conta_id BIGINT
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
  SELECT NOT EXISTS (
    SELECT 1
    FROM public.contas_ocultas_usuario o
    WHERE o.conta_id = p_conta_id
      AND o.user_id = (SELECT auth.uid())
  );
$function$;

REVOKE ALL ON FUNCTION public.conta_visivel_para_usuario(BIGINT)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.conta_visivel_para_usuario(BIGINT)
  TO authenticated, service_role;

-- Policies permissivas sao combinadas com OR. Uma policy RESTRICTIVE e
-- necessaria para que a ocultacao seja aplicada tambem sobre owner_all.
DROP POLICY IF EXISTS contas_not_hidden_select ON public.contas;
CREATE POLICY contas_not_hidden_select
  ON public.contas
  AS RESTRICTIVE
  FOR SELECT
  TO authenticated
  USING (public.conta_visivel_para_usuario(id));

CREATE OR REPLACE FUNCTION public.get_meu_resumo_dissolucao()
RETURNS TABLE (
  resumo_id BIGINT,
  parceria_id BIGINT,
  iniciada_por UUID,
  criado_em TIMESTAMPTZ,
  itens JSONB
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
  SELECT
    r.id,
    r.parceria_id,
    r.iniciada_por,
    r.created_at,
    COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'id', i.id,
          'tipo', i.tipo,
          'source_id', i.source_id,
          'source_owner_id', i.source_owner_id,
          'nome', i.nome,
          'saldo_final', i.saldo_final,
          'possui_lancamentos', i.possui_lancamentos,
          'estado', i.estado
        )
        ORDER BY CASE WHEN i.tipo = 'conta' THEN 0 ELSE 1 END, i.id
      )
      FROM public.parceria_dissolucao_itens i
      WHERE i.resumo_id = r.id
    ), '[]'::jsonb)
  FROM public.parceria_dissolucao_resumos r
  WHERE r.user_id = (SELECT auth.uid())
    AND r.visto_em IS NULL
  ORDER BY r.created_at, r.id
  LIMIT 1;
$function$;

CREATE OR REPLACE FUNCTION public.confirmar_resumo_dissolucao(p_resumo_id BIGINT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_uid UUID := auth.uid();
  v_updated INTEGER := 0;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'authentication required';
  END IF;

  UPDATE public.parceria_dissolucao_resumos
     SET visto_em = COALESCE(visto_em, now())
   WHERE id = p_resumo_id
     AND user_id = v_uid;

  GET DIAGNOSTICS v_updated = ROW_COUNT;
  RETURN v_updated = 1;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_minhas_decisoes_conta_dissolucao()
RETURNS TABLE (
  id BIGINT,
  nome TEXT,
  saldo_final NUMERIC,
  possui_lancamentos BOOLEAN
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
  SELECT i.id, i.nome, i.saldo_final, i.possui_lancamentos
  FROM public.parceria_dissolucao_itens i
  JOIN public.parceria_dissolucao_resumos r ON r.id = i.resumo_id
  WHERE r.user_id = (SELECT auth.uid())
    AND i.tipo = 'conta'
    AND i.estado = 'pendente'
    AND i.target_conta_id IS NOT NULL
  ORDER BY r.created_at, i.id;
$function$;

CREATE OR REPLACE FUNCTION public.resolver_decisao_conta_dissolucao(
  p_item_id BIGINT,
  p_manter_ativa BOOLEAN
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_uid UUID := auth.uid();
  v_item public.parceria_dissolucao_itens%ROWTYPE;
  v_updated INTEGER := 0;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'authentication required';
  END IF;

  SELECT i.*
    INTO v_item
    FROM public.parceria_dissolucao_itens i
    JOIN public.parceria_dissolucao_resumos r ON r.id = i.resumo_id
   WHERE i.id = p_item_id
     AND i.tipo = 'conta'
     AND i.estado = 'pendente'
     AND i.target_conta_id IS NOT NULL
     AND r.user_id = v_uid
   FOR UPDATE OF i;

  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'pending account decision not found';
  END IF;

  UPDATE public.contas
     SET compartilhado = false,
         arquivado = NOT p_manter_ativa
   WHERE id = v_item.target_conta_id
     AND user_id = v_uid;

  GET DIAGNOSTICS v_updated = ROW_COUNT;
  IF v_updated <> 1 THEN
    RAISE EXCEPTION USING ERRCODE = 'P0002', MESSAGE = 'account not found';
  END IF;

  UPDATE public.parceria_dissolucao_itens
     SET estado = CASE WHEN p_manter_ativa THEN 'mantida' ELSE 'arquivada' END,
         resolved_at = now()
   WHERE id = v_item.id;
END;
$function$;

REVOKE ALL ON FUNCTION public.get_meu_resumo_dissolucao() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.confirmar_resumo_dissolucao(BIGINT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_minhas_decisoes_conta_dissolucao() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.resolver_decisao_conta_dissolucao(BIGINT, BOOLEAN) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_meu_resumo_dissolucao() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.confirmar_resumo_dissolucao(BIGINT) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_minhas_decisoes_conta_dissolucao() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.resolver_decisao_conta_dissolucao(BIGINT, BOOLEAN) TO authenticated, service_role;

-- A assinatura INTEGER é preservada para o aplicativo atual continuar
-- compatível. Toda a separação ocorre na mesma transação desta RPC.
CREATE OR REPLACE FUNCTION public.iniciar_dissolucao_parceria(p_parceria_id BIGINT)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_uid UUID := auth.uid();
  v_parceria public.parcerias%ROWTYPE;
  v_decisoes INTEGER := 0;
  v_resumo_solicitante BIGINT;
  v_resumo_convidado BIGINT;
  v_resumo_atual BIGINT;
  v_participante UUID;
  v_conta RECORD;
  v_saldo_pessoal NUMERIC;
  v_possui_lancamentos BOOLEAN;
  v_target_conta_id BIGINT;
  v_estado TEXT;
  v_arquivar BOOLEAN;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'authentication required';
  END IF;

  -- A IA usa a mesma trava antes de calcular/confirmar qualquer ação sobre
  -- recursos compartilhados. Assim a parceria não pode desaparecer entre a
  -- autorização e a escrita financeira, nem a dissolução pode observar uma
  -- movimentação parcialmente confirmada.
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('finflow:partnership:' || p_parceria_id::TEXT, 73119)
  );

  SELECT *
    INTO v_parceria
    FROM public.parcerias
   WHERE id = p_parceria_id
     AND status = 'aceito'
     AND (solicitante_id = v_uid OR convidado_id = v_uid)
   FOR UPDATE;

  IF NOT FOUND OR v_parceria.convidado_id IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'active partnership not found';
  END IF;

  INSERT INTO public.parceria_dissolucao_resumos (
    parceria_id, user_id, iniciada_por
  ) VALUES (
    v_parceria.id, v_parceria.solicitante_id, v_uid
  )
  RETURNING id INTO v_resumo_solicitante;

  INSERT INTO public.parceria_dissolucao_resumos (
    parceria_id, user_id, iniciada_por
  ) VALUES (
    v_parceria.id, v_parceria.convidado_id, v_uid
  )
  RETURNING id INTO v_resumo_convidado;

  -- Separa cada conta por participante. O saldo inicial pertence ao criador;
  -- receitas, despesas e transferências pertencem ao user_id do lançamento.
  FOR v_conta IN
    SELECT c.id, c.user_id, c.nome, c.saldo_inicial, c.cor
    FROM public.contas c
    WHERE c.compartilhado IS TRUE
      AND c.user_id IN (v_parceria.solicitante_id, v_parceria.convidado_id)
    ORDER BY c.id
    FOR UPDATE
  LOOP
    FOREACH v_participante IN ARRAY ARRAY[
      v_parceria.solicitante_id,
      v_parceria.convidado_id
    ]
    LOOP
      v_resumo_atual := CASE
        WHEN v_participante = v_parceria.solicitante_id THEN v_resumo_solicitante
        ELSE v_resumo_convidado
      END;

      SELECT
        (CASE WHEN v_participante = v_conta.user_id
          THEN COALESCE(v_conta.saldo_inicial, 0)
          ELSE 0
        END)
        + COALESCE((
          SELECT sum(
            CASE
              WHEN t.tipo = 'receita' THEN COALESCE(t.valor, 0)
              WHEN t.tipo = 'despesa' THEN -COALESCE(t.valor, 0)
              ELSE 0
            END
          )
          FROM public.transacoes t
          WHERE t.user_id = v_participante
            AND t.conta_id = v_conta.id
            AND t.status = 'paga'
        ), 0)
        + COALESCE((
          SELECT sum(COALESCE(t.valor, 0))
          FROM public.transacoes t
          WHERE t.user_id = v_participante
            AND t.status = 'paga'
            AND substring(COALESCE(t.descricao, '') FROM '\[Destino:([0-9]+)\]\s*$') = v_conta.id::text
        ), 0),
        EXISTS (
          SELECT 1
          FROM public.transacoes t
          WHERE t.user_id = v_participante
            AND (
              t.conta_id = v_conta.id
              OR substring(COALESCE(t.descricao, '') FROM '\[Destino:([0-9]+)\]\s*$') = v_conta.id::text
            )
        )
      INTO v_saldo_pessoal, v_possui_lancamentos;

      v_target_conta_id := NULL;
      v_estado := 'removida';

      IF v_participante = v_conta.user_id THEN
        v_target_conta_id := v_conta.id;
      ELSIF v_possui_lancamentos OR abs(v_saldo_pessoal) > 0.005 THEN
        INSERT INTO public.contas (
          nome, saldo_inicial, user_id, compartilhado, cor, arquivado
        ) VALUES (
          v_conta.nome, 0, v_participante, false, COALESCE(v_conta.cor, '#16966E'),
          v_possui_lancamentos
        )
        RETURNING id INTO v_target_conta_id;
      END IF;

      IF v_target_conta_id IS NOT NULL THEN
        IF v_possui_lancamentos THEN
          v_estado := 'pendente';
          v_arquivar := true;
        ELSIF abs(v_saldo_pessoal) > 0.005 THEN
          v_estado := 'mantida';
          v_arquivar := false;
        ELSE
          v_estado := 'removida';
          v_arquivar := true;
        END IF;

        UPDATE public.contas
           SET compartilhado = false,
               arquivado = v_arquivar
         WHERE id = v_target_conta_id
           AND user_id = v_participante;
      END IF;

      INSERT INTO public.parceria_dissolucao_itens (
        resumo_id, tipo, source_id, target_conta_id, source_owner_id,
        nome, saldo_final, possui_lancamentos, estado
      ) VALUES (
        v_resumo_atual, 'conta', v_conta.id, v_target_conta_id,
        v_conta.user_id, v_conta.nome, v_saldo_pessoal,
        v_possui_lancamentos, v_estado
      );
    END LOOP;
  END LOOP;

  -- Move cada lançamento para a conta individual do próprio autor. O mapa
  -- também inclui a conta original do criador, portanto nenhum caso especial é
  -- necessário aqui.
  UPDATE public.transacoes t
     SET conta_id = i.target_conta_id
    FROM public.parceria_dissolucao_itens i
    JOIN public.parceria_dissolucao_resumos r ON r.id = i.resumo_id
   WHERE r.parceria_id = v_parceria.id
     AND r.user_id = t.user_id
     AND i.tipo = 'conta'
     AND i.source_id = t.conta_id
     AND i.target_conta_id IS NOT NULL
     AND t.conta_id IS DISTINCT FROM i.target_conta_id;

  -- Atualiza o destino das transferências com o mesmo mapa old -> target do
  -- autor, preservando transferências entre várias contas que foram clonadas.
  UPDATE public.transacoes t
     SET descricao = regexp_replace(
       t.descricao,
       '\[Destino:[0-9]+\]\s*$',
       format('[Destino:%s]', i.target_conta_id)
     )
    FROM public.parceria_dissolucao_itens i
    JOIN public.parceria_dissolucao_resumos r ON r.id = i.resumo_id
   WHERE r.parceria_id = v_parceria.id
     AND r.user_id = t.user_id
     AND i.tipo = 'conta'
     AND i.target_conta_id IS NOT NULL
     AND substring(COALESCE(t.descricao, '') FROM '\[Destino:([0-9]+)\]\s*$') = i.source_id::text;

  -- Zero sem lancamentos deve sumir das listas do participante, inclusive do
  -- hub de arquivadas, mas o registro continua recuperavel no banco. O mapa e
  -- gravado somente quando a conta-alvo realmente pertence ao destinatario do
  -- resumo; assim a ocultacao nunca vaza de um participante para o outro.
  INSERT INTO public.contas_ocultas_usuario (
    conta_id, user_id, resumo_id, motivo
  )
  SELECT
    i.target_conta_id,
    r.user_id,
    r.id,
    'dissolucao_parceria'
  FROM public.parceria_dissolucao_itens i
  JOIN public.parceria_dissolucao_resumos r ON r.id = i.resumo_id
  JOIN public.contas c
    ON c.id = i.target_conta_id
   AND c.user_id = r.user_id
  WHERE r.parceria_id = v_parceria.id
    AND i.tipo = 'conta'
    AND i.estado = 'removida'
    AND i.target_conta_id IS NOT NULL
  ON CONFLICT (conta_id, user_id) DO NOTHING;

  -- Fotografia dos objetivos. A escolha do saldo individual continua sendo
  -- feita pelas decisões atômicas de parceria_caixinha_decisoes.
  WITH destinatarios(user_id, resumo_id) AS (
    VALUES
      (v_parceria.solicitante_id, v_resumo_solicitante),
      (v_parceria.convidado_id, v_resumo_convidado)
  )
  INSERT INTO public.parceria_dissolucao_itens (
    resumo_id, tipo, source_id, target_conta_id, source_owner_id,
    nome, saldo_final, possui_lancamentos, estado
  )
  SELECT
    d.resumo_id,
    'caixinha',
    c.id,
    NULL,
    c.user_id,
    c.nome,
    greatest(0, COALESCE(c.saldo_atual, 0)),
    false,
    'informativo'
  FROM public.caixinhas c
  CROSS JOIN destinatarios d
  WHERE c.compartilhado IS TRUE
    AND c.user_id IN (v_parceria.solicitante_id, v_parceria.convidado_id);

  INSERT INTO public.parceria_caixinha_decisoes (
    parceria_id,
    source_caixinha_id,
    user_id,
    source_owner_id,
    nome,
    meta_valor,
    saldo_total,
    cor,
    icone,
    data_prazo
  )
  SELECT
    v_parceria.id,
    c.id,
    participante.user_id,
    c.user_id,
    c.nome,
    c.meta_valor,
    greatest(0, COALESCE(c.saldo_atual, 0)),
    c.cor,
    c.icone,
    c.data_prazo
  FROM public.caixinhas c
  CROSS JOIN LATERAL (
    VALUES (v_parceria.solicitante_id), (v_parceria.convidado_id)
  ) AS participante(user_id)
  WHERE c.compartilhado IS TRUE
    AND c.user_id IN (v_parceria.solicitante_id, v_parceria.convidado_id)
  ON CONFLICT (parceria_id, source_caixinha_id, user_id) DO NOTHING;

  GET DIAGNOSTICS v_decisoes = ROW_COUNT;

  UPDATE public.caixinhas
     SET compartilhado = false,
         arquivado = true
   WHERE compartilhado IS TRUE
     AND user_id IN (v_parceria.solicitante_id, v_parceria.convidado_id);

  DELETE FROM public.parcerias WHERE id = v_parceria.id;

  RETURN v_decisoes;
END;
$function$;

REVOKE ALL ON FUNCTION public.iniciar_dissolucao_parceria(BIGINT)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.iniciar_dissolucao_parceria(BIGINT)
  TO authenticated, service_role;

COMMIT;
