-- FinFlow: eventos obrigatorios e persistentes do fluxo de parceria.
--
-- Estes avisos nao substituem push remoto. Eles ficam no banco e sao exibidos
-- assim que o destinatario abrir ou retomar o aplicativo.

BEGIN;

CREATE TABLE IF NOT EXISTS public.notificacoes_sistema (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  destinatario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL CHECK (
    tipo IN ('convite_parceria', 'parceria_aceita', 'parceria_recusada')
  ),
  referencia_id BIGINT NOT NULL,
  titulo TEXT NOT NULL,
  mensagem TEXT NOT NULL,
  dados JSONB NOT NULL DEFAULT '{}'::jsonb,
  criada_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  lida_em TIMESTAMPTZ,
  UNIQUE (destinatario_id, tipo, referencia_id)
);

CREATE INDEX IF NOT EXISTS notificacoes_sistema_destinatario_pendentes_idx
  ON public.notificacoes_sistema (destinatario_id, criada_em, id)
  WHERE lida_em IS NULL;

ALTER TABLE public.notificacoes_sistema ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.notificacoes_sistema FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.notificacoes_sistema TO authenticated;
GRANT ALL ON TABLE public.notificacoes_sistema TO service_role;

REVOKE ALL ON SEQUENCE public.notificacoes_sistema_id_seq FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.notificacoes_sistema_id_seq TO service_role;

DROP POLICY IF EXISTS notificacoes_sistema_owner_select
  ON public.notificacoes_sistema;
CREATE POLICY notificacoes_sistema_owner_select
  ON public.notificacoes_sistema
  FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = destinatario_id);

-- A leitura e confirmada por RPC para que o cliente nao tenha UPDATE livre na
-- tabela, nem mesmo sobre os proprios titulos/destinatarios.
CREATE OR REPLACE FUNCTION public.marcar_notificacao_sistema_lida(p_id BIGINT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_uid UUID := auth.uid();
  v_atualizadas INTEGER := 0;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'authentication required';
  END IF;

  UPDATE public.notificacoes_sistema
     SET lida_em = COALESCE(lida_em, now())
   WHERE id = p_id
     AND destinatario_id = v_uid;

  GET DIAGNOSTICS v_atualizadas = ROW_COUNT;
  RETURN v_atualizadas = 1;
END;
$function$;

REVOKE ALL ON FUNCTION public.marcar_notificacao_sistema_lida(BIGINT)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.marcar_notificacao_sistema_lida(BIGINT)
  TO authenticated, service_role;

-- Registra cada mudanca de parceria na mesma transacao da acao original.
-- O cliente nao recebe permissao para criar eventos, evitando avisos forjados.
CREATE OR REPLACE FUNCTION public.registrar_evento_obrigatorio_parceria()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
  v_ator UUID := auth.uid();
  v_convidado_id UUID;
  v_solicitante_nome TEXT;
  v_convidado_nome TEXT;
BEGIN
  IF TG_OP = 'INSERT' THEN
    SELECT u.id
      INTO v_convidado_id
      FROM auth.users u
     WHERE lower(u.email) = lower(NEW.convidado_email)
     ORDER BY u.created_at
     LIMIT 1;

    -- O proprio app informa que o parceiro precisa estar cadastrado. Falhar a
    -- transacao aqui evita um convite que jamais poderia ser entregue.
    IF v_convidado_id IS NULL THEN
      RAISE EXCEPTION USING
        ERRCODE = 'P0002',
        MESSAGE = 'finflow_invitee_not_found';
    END IF;

    SELECT COALESCE(
             NULLIF(btrim(u.raw_user_meta_data ->> 'nome_usuario'), ''),
             NULLIF(btrim(u.raw_user_meta_data ->> 'full_name'), ''),
             split_part(COALESCE(u.email, ''), '@', 1),
             'Um usuário'
           )
      INTO v_solicitante_nome
      FROM auth.users u
     WHERE u.id = NEW.solicitante_id;

    INSERT INTO public.notificacoes_sistema (
      destinatario_id, tipo, referencia_id, titulo, mensagem, dados
    ) VALUES (
      v_convidado_id,
      'convite_parceria',
      NEW.id,
      'Convite de parceria',
      format('%s convidou você para vincular as contas no FinFlow.', v_solicitante_nome),
      jsonb_build_object(
        'parceria_id', NEW.id,
        'solicitante_id', NEW.solicitante_id,
        'solicitante_nome', v_solicitante_nome,
        'acao', 'abrir_convite'
      )
    )
    ON CONFLICT (destinatario_id, tipo, referencia_id) DO NOTHING;

    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE'
     AND OLD.status = 'pendente'
     AND NEW.status = 'aceito' THEN
    SELECT COALESCE(
             NULLIF(btrim(u.raw_user_meta_data ->> 'nome_usuario'), ''),
             NULLIF(btrim(u.raw_user_meta_data ->> 'full_name'), ''),
             split_part(COALESCE(u.email, ''), '@', 1),
             'Seu parceiro'
           )
      INTO v_convidado_nome
      FROM auth.users u
     WHERE u.id = NEW.convidado_id;

    -- O convite deixa de ser pendente para quem acabou de responder.
    UPDATE public.notificacoes_sistema
       SET lida_em = COALESCE(lida_em, now())
     WHERE destinatario_id = NEW.convidado_id
       AND tipo = 'convite_parceria'
       AND referencia_id = NEW.id;

    INSERT INTO public.notificacoes_sistema (
      destinatario_id, tipo, referencia_id, titulo, mensagem, dados
    ) VALUES (
      NEW.solicitante_id,
      'parceria_aceita',
      NEW.id,
      'Parceria formada!',
      format('%s aceitou seu convite. Agora vocês podem usar os recursos compartilhados.', v_convidado_nome),
      jsonb_build_object(
        'parceria_id', NEW.id,
        'convidado_id', NEW.convidado_id,
        'convidado_nome', v_convidado_nome
      )
    )
    ON CONFLICT (destinatario_id, tipo, referencia_id) DO NOTHING;

    RETURN NEW;
  END IF;

  IF TG_OP = 'DELETE' AND OLD.status = 'pendente' THEN
    SELECT u.id,
           COALESCE(
             NULLIF(btrim(u.raw_user_meta_data ->> 'nome_usuario'), ''),
             NULLIF(btrim(u.raw_user_meta_data ->> 'full_name'), ''),
             split_part(COALESCE(u.email, ''), '@', 1),
             'O convidado'
           )
      INTO v_convidado_id, v_convidado_nome
      FROM auth.users u
     WHERE lower(u.email) = lower(OLD.convidado_email)
     ORDER BY u.created_at
     LIMIT 1;

    -- Tanto a recusa quanto o cancelamento encerram o aviso do convidado.
    IF v_convidado_id IS NOT NULL THEN
      UPDATE public.notificacoes_sistema
         SET lida_em = COALESCE(lida_em, now())
       WHERE destinatario_id = v_convidado_id
         AND tipo = 'convite_parceria'
         AND referencia_id = OLD.id;
    END IF;

    -- Quem enviou apenas cancela. Uma exclusao feita pelo e-mail convidado e
    -- uma recusa e precisa avisar o solicitante.
    IF v_ator IS NOT NULL AND v_ator <> OLD.solicitante_id THEN
      INSERT INTO public.notificacoes_sistema (
        destinatario_id, tipo, referencia_id, titulo, mensagem, dados
      ) VALUES (
        OLD.solicitante_id,
        'parceria_recusada',
        OLD.id,
        'Convite recusado',
        format('%s recusou seu convite de parceria.', v_convidado_nome),
        jsonb_build_object(
          'parceria_id', OLD.id,
          'convidado_id', v_convidado_id,
          'convidado_nome', v_convidado_nome
        )
      )
      ON CONFLICT (destinatario_id, tipo, referencia_id) DO NOTHING;
    END IF;

    RETURN OLD;
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION public.registrar_evento_obrigatorio_parceria()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS registrar_evento_obrigatorio_parceria
  ON public.parcerias;
CREATE TRIGGER registrar_evento_obrigatorio_parceria
  AFTER INSERT OR UPDATE OR DELETE ON public.parcerias
  FOR EACH ROW EXECUTE FUNCTION public.registrar_evento_obrigatorio_parceria();

-- Convites que ja estavam pendentes antes desta migration tambem passam a ser
-- visiveis no centro global de avisos.
INSERT INTO public.notificacoes_sistema (
  destinatario_id, tipo, referencia_id, titulo, mensagem, dados
)
SELECT
  convidado.id,
  'convite_parceria',
  p.id,
  'Convite de parceria',
  format('%s convidou você para vincular as contas no FinFlow.',
    COALESCE(
      NULLIF(btrim(solicitante.raw_user_meta_data ->> 'nome_usuario'), ''),
      NULLIF(btrim(solicitante.raw_user_meta_data ->> 'full_name'), ''),
      split_part(COALESCE(solicitante.email, ''), '@', 1),
      'Um usuário'
    )
  ),
  jsonb_build_object(
    'parceria_id', p.id,
    'solicitante_id', p.solicitante_id,
    'acao', 'abrir_convite'
  )
FROM public.parcerias p
JOIN auth.users convidado
  ON lower(convidado.email) = lower(p.convidado_email)
LEFT JOIN auth.users solicitante
  ON solicitante.id = p.solicitante_id
WHERE p.status = 'pendente'
ON CONFLICT (destinatario_id, tipo, referencia_id) DO NOTHING;

COMMIT;
